package reporter

import (
	"fmt"
	"os"
	"strings"

	"github.com/Al-Gharbi/smart-audit/internal/analyzer"
)

type MarkdownReporter struct{}

func (m *MarkdownReporter) Generate(report *analyzer.AuditReport, outputPath string) error {
	var b strings.Builder

	s := report.Summary
	fmt.Fprintf(&b, "# %s\n\n", report.Title)
	fmt.Fprintf(&b, "**Generated:** %s  \n**Duration:** %s  \n**Tool:** smart-audit v%s\n\n", report.Timestamp, report.Duration, report.Version)
	fmt.Fprintf(&b, "---\n\n## Executive Summary\n\n")
	fmt.Fprintf(&b, "| Metric | Count |\n|---|---|\n")
	fmt.Fprintf(&b, "| Contracts Scanned | %d |\n", s.TotalContracts)
	fmt.Fprintf(&b, "| Total Findings | %d |\n", s.TotalFindings)
	fmt.Fprintf(&b, "| 🔴 Critical | %d |\n", s.Critical)
	fmt.Fprintf(&b, "| 🟠 High | %d |\n", s.High)
	fmt.Fprintf(&b, "| 🟡 Medium | %d |\n", s.Medium)
	fmt.Fprintf(&b, "| 🔵 Low | %d |\n", s.Low)
	fmt.Fprintf(&b, "| ⚪ Info | %d |\n", s.Info)
	fmt.Fprintf(&b, "| **Overall Risk** | **%s** |\n\n", s.OverallRisk)

	fmt.Fprintf(&b, "---\n\n## Findings by Contract\n\n")

	for _, c := range report.Contracts {
		fmt.Fprintf(&b, "### 📄 %s\n\n", c.FileName)
		fmt.Fprintf(&b, "- **Lines of Code:** %d\n- **Solidity Version:** `%s`\n- **Risk Score:** %.1f / 10\n- **Findings:** %d\n\n",
			c.LinesOfCode, c.SolidityVersion, c.RiskScore, len(c.Findings))

		if len(c.Findings) == 0 {
			fmt.Fprintf(&b, "✅ No issues detected by the current rule set.\n\n")
			continue
		}

		for _, f := range c.Findings {
			fmt.Fprintf(&b, "#### [%s] %s\n\n", f.Severity, f.Title)
			fmt.Fprintf(&b, "| | |\n|---|---|\n")
			fmt.Fprintf(&b, "| **ID** | %s |\n", f.ID)
			if f.SWC != "" {
				fmt.Fprintf(&b, "| **SWC** | %s |\n", f.SWC)
			}
			if f.CWE != "" {
				fmt.Fprintf(&b, "| **CWE** | %s |\n", f.CWE)
			}
			fmt.Fprintf(&b, "| **Location** | `%s:%d` |\n\n", f.File, f.Line)

			fmt.Fprintf(&b, "**Description**\n\n%s\n\n", f.Description)

			if f.CodeSnippet != "" {
				fmt.Fprintf(&b, "**Code**\n\n```solidity\n%s\n```\n\n", f.CodeSnippet)
			}

			fmt.Fprintf(&b, "**Recommendation**\n\n%s\n\n", f.Recommendation)

			if len(f.References) > 0 {
				fmt.Fprintf(&b, "**References**\n\n")
				for _, r := range f.References {
					fmt.Fprintf(&b, "- %s\n", r)
				}
				fmt.Fprintf(&b, "\n")
			}
			fmt.Fprintf(&b, "---\n\n")
		}
	}

	fmt.Fprintf(&b, "\n*Generated by [smart-audit](https://github.com/Al-Gharbi/smart-audit) — automated static analysis. ")
	fmt.Fprintf(&b, "Always combine automated tools with manual review before mainnet deployment.*\n")

	return os.WriteFile(outputPath, []byte(b.String()), 0644)
}
